name: Push on dev branch

on:
  push:
    branches:
      - dev

jobs:
  print-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print branch name
        run: |
          echo "Push on dev branch"